### ISSUE TITLE
Kong.plugin.create() fails for Kong >= 2.0.0

### ISSUE THREAD

**Issue by penguin2716** [coderade/node-kong-admin-ts#1]
Kong.plugin.create() and its related methods fail for Kong >= 2.0.0. Kong removed the `run_on` property on the plugin object from 2.0.0. If the request body contains the property, Kong returns 400 Bad Request because of the schema violation.

```json
{
  "message": "schema violation (run_on: unknown field)",
  "code": 2,
  "fields": {
    "run_on": "unknown field"
  },
  "name": "schema violation"
}
```

Simply deleting the default value for the `run_on` property (` || 'first'`) from the code below solved the problem in my environment, and it may hold the backward compatibility.
https://github.com/coderade/node-kong-admin-ts/blob/6e721cce30dce35c44343ed184c9ca9469a782e2/src/validators/data.validator.ts#L103

Kong Admin API reference for 1.5.x and 2.0.x:
- https://docs.konghq.com/gateway-oss/1.5.x/admin-api/
- https://docs.konghq.com/gateway-oss/2.0.x/admin-api/

**Comment by coderade** [comment]
Hi  @penguin2716, in the time that I created the project I was using kong <= 2.0.0.

Do you min in create a pull request?

**Comment by coderade** [comment]
Thanks for your comment @penguin2716.

A fix has been done and new version has been published in the [npm](https://www.npmjs.com/package/@coderade/node-kong-admin-ts)
